import React, {useEffect, useState} from "react";
import {ChartMark, ChartTooltip, DataComponent, Dropdown, EvidenceChart, ReportSection, RichNarrative, useDataApp} from "../../data-app-public.jsx";
import "./report.css";

const fmt=(n,d=2)=>n==null?"—":typeof n==="number"?n.toLocaleString("zh-CN",{minimumFractionDigits:d,maximumFractionDigits:d}):String(n);
function Table({rows,columns}){return <div className="discussion-table-scroll"><table className="discussion-table" data-reviewed-rows><thead><tr>{columns.map(([k,l])=><th key={k}>{l}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{columns.map(([k,,d=2])=><td key={k} className={typeof r[k]==="number"?"number":undefined}>{fmt(r[k],d)}</td>)}</tr>)}</tbody></table></div>;}
function Copy({id,text}){return <RichNarrative id={id} value={text}/>;}
function Empty({text="尚未绑定证据。填入真实数据后，这里显示相应图表；空白不代表数值为零。"}){return <div className="empty-evidence">{text}</div>;}
function narrativeList(value){return Array.isArray(value)?value.map(v=>`- ${typeof v==="string"?v:JSON.stringify(v)}`).join("\n"):value??"";}
function OptionCard({option,id}){return <div className="option"><span className="option-status" data-reviewed-rows>{option.status_label??option.status??"待讨论，未验证"}</span><Copy id={`${id}-name`} text={`#### ${option.id} · ${option.label??option.title??option.id}`}/><Copy id={`${id}-body`} text={option.markdown??option.explanation??""}/></div>;}
function TariffChart({rows}){
 const max=Math.max(...rows.map(r=>r.price))*1.12;
 const segments=[];
 rows.forEach((row,index)=>{const last=segments[segments.length-1];if(last&&last.price===row.price){last.end=index+1;}else segments.push({start:index,end:index+1,price:row.price,time:row.time});});
 const path=rows.map((r,i)=>`${i?"L":"M"}${i/144*1000},${200-r.price/max*200} H${(i+1)/144*1000}`).join(" ");
 const endTime=index=>index===144?"24:00":rows[index].time;
 return <DataComponent id="tariff-chart" queryId="tariff" kind="custom" title="附件1 · 一天的固定电价" sourceRows={rows} displayRows={rows}><div className="tariff-step-chart" data-chart-interaction-root data-reviewed-rows><span className="tariff-unit">元/kWh</span><div className="tariff-step-plot"><svg width="100%" height="100%" viewBox="0 0 1000 200" preserveAspectRatio="none" role="img" aria-label="正常电价阶梯图，各10分钟区间内电价固定"><path d={path} fill="none" stroke="var(--chart-1)" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg>{segments.map((r,i)=><ChartMark key={i} className="tariff-step-mark" style={{left:`${r.start/144*100}%`,width:`${(r.end-r.start)/144*100}%`}} aria-label={`${r.time}至${endTime(r.end)}，正常电价${r.price}元每千瓦时`} context={{kind:"chart",chartType:"step",label:`${r.time}—${endTime(r.end)}`,value:r.price,row:r}} tooltip={<ChartTooltip active label={`${r.time}—${endTime(r.end)}`} details={[{label:"正常电价",value:`${fmt(r.price,3)} 元/kWh`}]} />}/>)}{[0,1,2,3,4].map(i=><span className="tariff-y-tick" style={{top:`${100-i*25}%`}} key={i}>{fmt(max*i/4,2)}</span>)}{[0,6,12,18,24].map(hour=><span className="tariff-x-tick" style={{left:`${hour/24*100}%`}} key={hour}>{String(hour).padStart(2,"0")}:00</span>)}</div></div></DataComponent>;
}
function ModuleBlock({module,rows}){return <section className="module" id={`module-${module.id}`}><DataComponent id={`module-source-${module.id}`} queryId="module_options" kind="custom" title={module.title} sourceRows={rows} displayRows={rows}><details><summary><span>{module.id} · {module.title}</span></summary><div className="module-intro"><Copy id={`${module.id}-intro`} text={module.summary??module.question??""}/></div><div className="module-interface"><div><Copy id={`${module.id}-input`} text={`**接收什么**\n\n${narrativeList(module.inputs??module.input)}`}/></div><div><Copy id={`${module.id}-output`} text={`**交付什么**\n\n${narrativeList(module.outputs??module.output)}`}/></div></div><Copy id={`${module.id}-responsibility`} text={module.responsibility_markdown??""}/><Copy id={`${module.id}-foundation`} text={module.foundation_markdown??""}/>{(module.decisions??[]).map(decision=><div key={decision.id} className="decision-group"><Copy id={`${decision.id}-question`} text={`### ${decision.id} · ${decision.title??decision.question}\n\n${decision.context??""}`}/><div className="module-options">{decision.options.map(option=><OptionCard key={option.id} id={`${decision.id}-${option.id}`} option={option}/>)}</div>{decision.current&&<Copy id={`${decision.id}-current`} text={`**现有做法**：${decision.current}`}/>}</div>)}{module.options?.length>0&&<div className="module-options">{module.options.map(option=><OptionCard key={option.id} id={`${module.id}-${option.id}`} option={option}/>)}</div>}<Copy id={`${module.id}-acceptance`} text={module.acceptance_markdown??""}/></details></DataComponent><div className="module-intro"><Copy id={`${module.id}-short-summary`} text={module.summary??module.question??""}/></div></section>;}
function Meeting({modules,artifactId,template}){
 const storageKey=`q2-discussion-meeting:${artifactId}`;
 const blank={meeting_date:"",participants:"",overall_notes:"",choices:{},owners:{},rationales:{}};
 const [draft,setDraft]=useState(()=>{try{return {...blank,...JSON.parse(localStorage.getItem(storageKey)||"{}")};}catch{return blank;}});
 const [message,setMessage]=useState("");
 useEffect(()=>{try{localStorage.setItem(storageKey,JSON.stringify(draft));}catch{setMessage("浏览器未允许本地保存，请导出会议草稿。");}},[storageKey,draft]);
 const update=(key,val)=>setDraft(d=>({...d,[key]:val}));
 const nested=(key,id,val)=>setDraft(d=>({...d,[key]:{...d[key],[id]:val}}));
 const exportDraft=()=>{const payload={schema_version:1,artifact_id:artifactId,kind:"discussion_draft",model_changed:false,template,exported_at:new Date().toISOString(),...draft,options_catalog:modules.flatMap(m=>(m.decisions??[]).map(d=>({module_id:m.id,decision_id:d.id,title:d.title??d.question,options:d.options.map(o=>({id:o.id,label:o.label??o.title,status:o.status_label??o.status}))})))};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="q2-discussion-draft.json";link.click();URL.revokeObjectURL(url);setMessage("已导出会议草稿。此草稿没有修改模型、配置或实验记录。");};
 return <><Copy id="meeting-guidance" text="## 06 · 把本次讨论留下来\n\n每个技术问题先保留为“待讨论”。选项只是会议意向；填写负责人、理由后可导出 JSON 草稿交给下一轮实验。选择会保存在当前浏览器，刷新后保留，不会改动任何模型或自动开始训练。"/><div className="meeting-grid"><label className="meeting-field">会议日期<input type="date" value={draft.meeting_date} onChange={e=>update("meeting_date",e.target.value)}/></label><label className="meeting-field">参与者<input value={draft.participants} onChange={e=>update("participants",e.target.value)} placeholder="填写本次参加讨论的成员"/></label></div>{modules.map(m=><div key={m.id} className="decision-group"><Copy id={`meeting-${m.id}-title`} text={`### ${m.id} · ${m.title}`}/><div className="meeting-grid"><label className="meeting-field">负责人<input value={draft.owners[m.id]??""} onChange={e=>nested("owners",m.id,e.target.value)} placeholder="暂不指定可留空"/></label>{(m.decisions??[]).map(d=><label key={d.id} className="meeting-field">{d.id} · {d.title??d.question}<select value={draft.choices[d.id]??""} onChange={e=>nested("choices",d.id,e.target.value)}><option value="">待讨论，尚未选择</option>{d.options.map(o=><option key={o.id} value={o.id}>{o.id} · {o.label??o.title}</option>)}</select></label>)}</div><label className="meeting-field">选择理由、尚存疑问、需要补充的证据<textarea value={draft.rationales[m.id]??""} onChange={e=>nested("rationales",m.id,e.target.value)}/></label></div>)}<label className="meeting-field">会议结论与下一步交付<textarea value={draft.overall_notes} onChange={e=>update("overall_notes",e.target.value)} placeholder="写清先改哪个模块、保持哪些条件、比较哪些总费用。"/></label><div className="meeting-actions"><button type="button" className="meeting-action" onClick={exportDraft}>导出会议草稿 JSON</button><button type="button" className="meeting-action" onClick={()=>{setDraft(blank);setMessage("已清空当前浏览器中的会议草稿。");}}>清空本地草稿</button><span className="meeting-status" role="status">{message||"尚未实施任何新技术选择"}</span></div></>;
}
export function ReportContent(){
 const {snapshot,appTitle,canEdit,mode,setAppTitle}=useDataApp();
 const q=id=>snapshot.queries?.[id]?.rows??[];
 const modules=snapshot.discussion?.modules??[];
 const [month,setMonth]=useState("all"),[rawDay,setRawDay]=useState(snapshot.discussion?.rawDefaultDate??"2025-03-20"),[dispatchDay,setDispatchDay]=useState(snapshot.discussion?.dispatchDates?.[0]??"2025-03-20");
 const template=!!snapshot.discussion?.template;
 const annual=q("cost_annual"),monthly=q("cost_monthly"),sourceCosts=month==="all"?annual:monthly.filter(r=>String(r.month)===month);
 const costs=sourceCosts.map(r=>({...r,short_label:({v2_primary:"v2",exp003_uncalibrated:"未校准网络",exp003_primary:"当前方案",periodic:"周期基线"})[r.id]??r.label,total_wan:r.total_cost/10000,planned_wan:r.planned_cost/10000,emergency_wan:r.emergency_cost/10000}));
 const costQuery=month==="all"?"cost_annual":"cost_monthly";
 const rawRows=q("raw_daily").filter(r=>r.date===rawDay),dayRows=q("dispatch_intervals").filter(r=>r.date===dispatchDay),socRows=q("dispatch_states").filter(r=>r.date===dispatchDay),daySummary=q("dispatch_summary").filter(r=>r.date===dispatchDay);
 const months=[...new Set(monthly.map(r=>String(r.month)))];
 const dates=snapshot.discussion?.rawDates??[];
 const intro=snapshot.discussion?.intro??"";
 const sections=[["target","题意与目标"],["data","可用数据"],["cost","现有费用"],["modules","模块与选项"],["outputs","题目输出"],["meeting","会议记录"]];
 return <article className="report-content q2-discussion" aria-label={template?"第二问人工讨论空模板":"第二问人工讨论报告"}>
 <header className="discussion-hero"><h1 data-data-app-title contentEditable={canEdit&&mode==="edit"} suppressContentEditableWarning onBlur={canEdit&&mode==="edit"?e=>setAppTitle(e.currentTarget.textContent.trim()||appTitle):undefined}>{appTitle}</h1><Copy id="discussion-intro" text={intro}/></header>
 <nav className="discussion-nav" aria-label="报告章节">{sections.map(([id,title])=><a key={id} href={`#${id}`}>{title}</a>)}</nav>
 <section id="target" className="discussion-section"><Copy id="target-text" text={snapshot.discussion?.targetMarkdown??""}/><DataComponent id="frozen-contract" queryId="frozen_contract" kind="table" title="一起确认的边界条件" sourceRows={q("frozen_contract")} displayRows={q("frozen_contract")}><Table rows={q("frozen_contract")} columns={[["item","事项"],["meaning","题意和当前解释"],["effect","影响哪一步"]]}/></DataComponent></section>
 <section id="data" className="discussion-section"><Copy id="data-introduction" text="## 02 · 先看题目给了什么数据\n\n每天 144 个时间段，每段 10 分钟。负载功率表示这一刻用电的速度，光伏功率表示发电的速度，单位均为 kW。每段电量 = 功率 × 1/6 小时，单位为 kWh；把这些电量相加才得到月度用电量与发电量。月图为了方便阅读采用 MWh，**1 MWh = 1000 kWh**。"/>{q("tariff").length?<TariffChart rows={q("tariff")}/>:<Empty/>}{q("raw_monthly").length?<EvidenceChart id="raw-monthly-chart" queryId="raw_monthly" title="附件2 · 原始数据各月负载与光伏电量（1—12月）" rows={q("raw_monthly")} sourceRows={q("raw_monthly")} spec={{type:"horizontalBar",x:"month_label",y:"load_mwh",fields:["load_mwh","pv_mwh"],yLabel:"MWh",legend:{labels:{load_mwh:"负载电量",pv_mwh:"光伏电量"}},stackable:false}} height={560}/>:<Empty/>}{rawRows.length?<EvidenceChart id="raw-day-chart" queryId="raw_daily" title={`附件2 · ${rawDay} 的原始负载与光伏功率`} rows={rawRows} sourceRows={rawRows} headerControls={<Dropdown label="原始数据日期" showLabel value={rawDay} choices={dates} onChange={setRawDay}/>} spec={{type:"line",x:"time",y:"load_kw",fields:["load_kw","pv_kw"],yLabel:"kW",stackable:false,legend:{labels:{load_kw:"实际负载",pv_kw:"实际光伏"}}}} height={340}/>:<Empty/>}<Copy id="raw-observation" text={snapshot.discussion?.rawMarkdown??"原始数据覆盖 365 天。正式策略费用只比较 2—12 月，1 月用于训练与共同预热，不计入下面的正式费用。"}/></section>
 <section id="cost" className="discussion-section"><Copy id="cost-introduction" text={snapshot.discussion?.costMarkdown??"## 03 · 只按题目要求的购电费用比较\n\n总购电费 = 按原计划购买电量的费用 + 实际供电不足时的紧急购电费。图中的两项能相加，总费用是本次讨论判断是否改进的依据。"}/>{costs.length?<><EvidenceChart id="cost-components" queryId={costQuery} title={`各策略购电费用（万元） · ${month==="all"?"2—12月334天":`${month}月`}`} rows={costs} sourceRows={sourceCosts} headerControls={<Dropdown label="费用范围" showLabel value={month} choices={["all",...months]} choiceLabels={{all:"2—12月全部",...Object.fromEntries(months.map(m=>[m,`${m}月`]))}} onChange={setMonth}/>} spec={{type:"horizontalStackedBar",x:"short_label",y:"planned_wan",fields:["planned_wan","emergency_wan"],yLabel:"万元",valueDecimals:3,legend:{labels:{planned_wan:"计划购电费",emergency_wan:"紧急购电费"}}}} height={350}/><DataComponent id="cost-exact-table" queryId={costQuery} kind="table" title="费用精确值（元）" sourceRows={sourceCosts} displayRows={sourceCosts}><Table rows={sourceCosts} columns={[["label","策略"],["planned_cost","计划购电费"],["emergency_cost","紧急购电费"],["total_cost","总购电费"]]}/></DataComponent><EvidenceChart id="monthly-cost-chart" queryId="cost_monthly" title="每月总购电费 · 所有正式月份" rows={monthly.map(r=>({...r,total_wan:r.total_cost/10000}))} sourceRows={monthly} spec={{type:"line",x:"month_label",y:"total_wan",series:"label",yLabel:"万元",valueDecimals:3,stackable:false}} height={350}/></>:<Empty/>}<Copy id="cost-caveat" text={snapshot.discussion?.costCaveat??""}/></section>
 <section id="modules" className="discussion-section"><Copy id="modules-introduction" text="## 04 · 把第二问拆成可以并行负责的模块\n\n先统一每个模块接收和交付的数据，再决定内部采用哪种方法。只有午夜计划模块能生成当天购电计划；执行模块面对真实到来的负载和光伏。改进候选必须经过同一回放模块计算总购电费，才能与现有结果比较。点击每个模块可阅读完整技术选项。"/><DataComponent id="module-dependency-map" queryId="modules" kind="custom" title="分工与依赖：按交付物衔接" sourceRows={q("modules")} displayRows={q("modules")}><div className="discussion-flow" data-reviewed-rows>{modules.map(m=><a className="flow-node" key={m.id} href={`#module-${m.id}`}><strong>{m.id} · {m.title}</strong><small>{m.depends_on?.length?`接收 ${m.depends_on.join("、")} 的交付`:(m.dependency_label??"先统一题意、数据和单位")}</small></a>)}</div></DataComponent><Copy id="module-parallelism" text={snapshot.discussion?.parallelMarkdown??""}/><DataComponent id="module-handoffs" queryId="handoffs" kind="table" title="模块交接时，具体交付什么" sourceRows={q("handoffs")} displayRows={q("handoffs")}><Table rows={q("handoffs")} columns={[["from","交付方"],["to","接收方"],["artifact","交付物"],["check","接收前检查"]]}/></DataComponent>{modules.map(m=><ModuleBlock key={m.id} module={m} rows={q("module_options").filter(r=>r.module_id===m.id)}/>)}</section>
 <section id="outputs" className="discussion-section"><Copy id="outputs-introduction" text={template?"## 05 · 对照题目要求的表1—表3检查一天\n\n绑定已运行方案的执行证据后，这里展示指定日期的实际输出。表1给出计划购电与紧急购电，表2给出储能充放电，表3列出紧急购电时段。储能曲线用于检查每段电量和跨日接续；目前尚未绑定执行结果。":"## 05 · 对照题目要求的表1—表3检查一天\n\n这部分展示当前 exp003 方案的实际执行结果。表1给出计划购电与紧急购电，表2给出储能充放电，表3列出紧急购电发生的时段。储能曲线记录每个时间段开始和结束时剩余的电量，便于检查电量如何跨日接续。"}/>{dayRows.length?<><div className="raw-controls"><Dropdown label="题目指定日／当前总费用最高日" showLabel value={dispatchDay} choices={snapshot.discussion?.dispatchDates??[]} choiceLabels={snapshot.discussion?.dispatchDateLabels??{}} onChange={setDispatchDay}/></div><DataComponent id="dispatch-day-cost" queryId="dispatch_summary" kind="table" title={`${dispatchDay} · 当日购电费（元）`} sourceRows={daySummary} displayRows={daySummary}><Table rows={daySummary} columns={[["planned_cost","计划购电费"],["emergency_cost","紧急购电费"],["total_cost","总购电费"]]}/></DataComponent><DataComponent id="dispatch-day-quantities" queryId="dispatch_summary" kind="table" title={`${dispatchDay} · 全天电量与首尾储电量（kWh）`} sourceRows={daySummary} displayRows={daySummary}><Table rows={daySummary} columns={[["planned_kwh","全天计划购电量"],["emergency_kwh","全天紧急购电量"],["charge_kwh","全天充电量"],["discharge_kwh","全天放电量"],["initial_soc","0时储电量"],["final_soc","24时储电量"]]}/></DataComponent><EvidenceChart id="dispatch-energy-chart" queryId="dispatch_intervals" title="每10分钟的购电量" rows={dayRows} sourceRows={dayRows} spec={{type:"line",x:"time",y:"planned_kwh",fields:["planned_kwh","emergency_kwh"],yLabel:"kWh",valueDecimals:2,stackable:false,legend:{labels:{planned_kwh:"原计划购电量",emergency_kwh:"紧急购电量"}}}} height={310}/><EvidenceChart id="dispatch-storage-chart" queryId="dispatch_intervals" title="每10分钟的充电量与放电量" rows={dayRows} sourceRows={dayRows} spec={{type:"line",x:"time",y:"charge_kwh",fields:["charge_kwh","discharge_kwh"],yLabel:"kWh",valueDecimals:2,stackable:false,legend:{labels:{charge_kwh:"充电量",discharge_kwh:"放电量"}}}} height={310}/><EvidenceChart id="dispatch-soc-chart" queryId="dispatch_states" title="储能剩余电量及允许范围" rows={socRows} sourceRows={socRows} spec={{type:"line",x:"time",y:"soc_kwh",fields:["soc_kwh","min_kwh","max_kwh"],yLabel:"kWh",valueDecimals:2,stackable:false,legend:{labels:{soc_kwh:"剩余电量",min_kwh:"下限1200",max_kwh:"上限10800"}}}} height={320}/>{[["output_table1","题目表1 · 六个指定10分钟时段的购电量（kWh）",[["period","时段"],["planned_kwh","计划购电量"],["emergency_kwh","紧急购电量"]]],["output_table2","题目表2 · 每4小时的充放电量（kWh）",[["period","时段"],["charge_kwh","充电量"],["discharge_kwh","放电量"]]],["output_table3","题目表3 · 紧急购电时段与电量（kWh）",[["period","时段"],["emergency_kwh","紧急购电量"]]]].map(([id,title,columns])=>{const rows=q(id).filter(r=>r.date===dispatchDay);return <DataComponent key={id} id={id} queryId={id} kind="table" title={title} sourceRows={rows} displayRows={rows}>{rows.length?<Table rows={rows} columns={columns}/>:<Empty text="本日没有发生紧急购电。"/>}</DataComponent>;})}</>:<Empty/>}</section>
 <section id="meeting" className="discussion-section"><Meeting modules={modules} artifactId={snapshot.id} template={template}/></section>
 <details className="discussion-disclosure"><summary>数据口径、复现方式与历史决策</summary><Copy id="method-notes" text={snapshot.discussion?.methodMarkdown??""}/><DataComponent id="historical-decisions" queryId="historical_decisions" kind="table" title="既有实验决策（不自动成为本次会议决定）" sourceRows={q("historical_decisions")} displayRows={q("historical_decisions")}><Table rows={q("historical_decisions")} columns={[["id","编号"],["choice","现有选择"],["origin","决定依据"]]}/></DataComponent></details>
 </article>;
}
